mycv/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

handler500 = 'mycv.apps.core.views.server_error'

urlpatterns = patterns(
    'mycv.apps.core.views', url(r'^$', TemplateView.as_view(template_name='about.html'), name='about'),
)
urlpatterns += patterns(
    'mycv.apps.projects.views',
    url(r'^resume/$', 'client_list_view', name='client_list'),
)

urlpatterns += patterns(
    'mycv.apps.projects.views',
    url(r'^projects/', include('mycv.apps.projects.urls', namespace='projects', app_name='projects')),
)

    #url(r'^404/$', TemplateView.as_view(template_name='404.html'), name='404'),
    #url(r'^500/$', TemplateView.as_view(template_name='500.html'), name='500'),
    #url(r'^502/$', TemplateView.as_view(template_name='502.html'), name='502'),
    #url(r'^humans.txt$', TemplateView.as_view(template_name='humans.txt'), name='humans'),
    #url(r'^robots.txt$', TemplateView.as_view(template_name='robots.txt'), name='robots'),

if 'grappelli' in settings.INSTALLED_APPS:
    urlpatterns += patterns(
        '',
        url(r'^grappelli/', include('grappelli.urls')),
    )

urlpatterns += patterns(
    '',
    (r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns += patterns(
            '',
            url(r'^__debug__/', include(debug_toolbar.urls)),
        )

mycv/apps/core/models.py
from django.db import models


class Address(models.Model):

    street_address = models.CharField(max_length=250, blank=True)
    street_address2 = models.CharField(max_length=250, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=50, null=True, blank=True)
    country = models.CharField(max_length=50, null=True, blank=True)
    zip_code = models.CharField(blank=True, max_length=10)

    def __unicode__(self):
        return "%s" % self.formatted_address

    @property
    def formatted_address(self):
        return "%s %s %s %s" % (self.street_address, self.city or '', self.state or '', self.zip_code or '')

mycv/apps/projects/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


class Client(models.Model):
    CLIENT_TITLE_CHOICES = (
        (1, _("Consultant")),
        (2, _("Lead Developer")),
        #(3, _("")),
        #(4, _("")),
    )
    applicant = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('applicant'),
        related_name="clients",
        null=True, blank=True,
    )
    title = models.IntegerField(max_length=2, choices=CLIENT_TITLE_CHOICES)
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=2000)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    start_date = models.DateField()
    end_date = models.DateField()
    website = models.URLField(blank=True, default='')
    order_index = models.IntegerField(default=0)
    is_draft = models.BooleanField(default=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('order_index', '-end_date',)


class ClientObjective(models.Model):
    title = models.CharField(max_length=500)
    client = models.ForeignKey(Client, related_name='objectives')
    order_index = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title


class Project(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=2000)
    stack_items = models.ManyToManyField("projects.StackItem")
    order_index = models.IntegerField(default=0)
    source_url = models.URLField(blank=True, default='')
    is_draft = models.BooleanField(default=True)
    client = models.ForeignKey(Client, related_name='projects', null=True, blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('order_index',)


class ProjectFeature(models.Model):
    name = models.CharField(max_length=500)
    project = models.ForeignKey(Project, related_name='features')

    def __unicode__(self):
        return self.name


class StackItem(models.Model):
    applicant = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('applicant'),
        related_name="stack_items",
        null=True, blank=True,
    )
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=250, blank=True, default='')

    def __unicode__(self):
        return self.name


class Skill(models.Model):
    applicant = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('applicant'),
        related_name="skills",
        null=True, blank=True,
    )
    category = models.ForeignKey('categories.Category', null=True, blank=True)
    description = models.TextField(max_length=500, blank=True, default='')

    def __unicode__(self):
        return self.description

mycv/apps/core/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.template import RequestContext

# Create your views here.
def server_error(request, template_name='500.html'):
    """
    500 error handler.

    Templates: `500.html`
    Context: None
    """
    return render_to_response(template_name, context_instance = RequestContext(request))

mycv/apps/core/templates/_experience.html
{% for client in client_list %}
<div class="module">
    <div class="resume-title row">
        <h4 class="left col-sm-8">
            {% if client.website %}
            <a target="_blank" href="{{ client.website  }}">{{ client.name }} </a>
            {% else %}
            {{ client.name }}
            {% endif %}

        </h4>
        <h4 class="right col-sm-4 hidden-xs">{{ client.city }}, {{ client.state }}</h4>
    </div>
    <div class="resume-subtitle row">
        <h5 class="left col-sm-4"> {{ client.get_title_display }} </h5>
        <h5 class="right col-sm-8 hidden-xs"> {{ client.start_date|date:"M" }} {{ client.start_date.year }} - {{ client.end_date|date:"M" }} {{ client.end_date.year }} </h5>
    </div>
    <ul>
        {% for objective in client.objectives.all %}
        <li>{{ objective.title }}</li>
        {% endfor %}
    </ul>
</div>
{% endfor %}

mycv/apps/core/templates/_skills.html
<ul>
    {% for skill in applicant.skills.all %}
    <li>{{ skill.description }}</li>
    {% endfor %}
</ul>

mycv/apps/core/templates/about.html
{% extends "base.html" %}
{% load staticfiles %}

{% block container %}
<div class="col col-sm-10 col-md-8 col-lg-6 content">
    <article class="resume">
    <section id="about">
        <div class="page-header no-top-margin"><h2>About</h2></div>
            <div class="row">
                <div class="col col-md-8 col-sm-12">

                    <div></div>

                    <div id="contact"><strong>Contact:</strong></div>
                    <a href="mailto:pkalinsky@greenlightgo.co">pkalinsky@greenlightgo.co</a>
                    <address>
                    4545 Center Blvd, Apt 406<br>
                    Long Island City, NY 11109<br>
                    </address>
                </div>

                <div class="col-md-4 hidden-sm">
                    <img src="{% static 'img/pk-200x212.png' %}" width="200" height="212" align="right" style="padding: 0 0 20px 20px;" alt="Philip Kalinsky"/>
                </div>
            </div>
    </section>
    </article>
</div>
{% endblock %}

mycv/apps/core/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Philip Kalinsky CV</title>

    <!-- Le styles -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style type="text/css">.wf-loading .logo,.wf-loading .sidebar,.wf-loading .container{visibility:hidden;}</style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    {% comment %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endcomment %}


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!--script type="text/javascript" src="//use.typekit.net/nmz7ecf.js"></script-->
    <!--script type="text/javascript">try{Typekit.load();}catch(e){}</script-->

   <script type="text/javascript">
      (function() {
        var config = {
          kitId: 'nmz7ecf',
          scriptTimeout: 3000
        };
        var h=document.getElementsByTagName("html")[0];h.className+=" wf-loading";var t=setTimeout(function(){h.className=h.className.replace(/(\s|^)wf-loading(\s|$)/g," ");h.className+=" wf-inactive"},config.scriptTimeout);var tk=document.createElement("script"),d=false;tk.src='//use.typekit.net/'+config.kitId+'.js';tk.type="text/javascript";tk.async="true";tk.onload=tk.onreadystatechange=function(){var a=this.readyState;if(d||a&&a!="complete"&&a!="loaded")return;d=true;clearTimeout(t);try{Typekit.load(config)}catch(b){}};var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(tk,s)
      })();
    </script>
</head>

 <body>
{% block navbar %}
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="logo">
        <a href="/"><h1><span class="camel">P</span>hilip <span class="camel">K</span>alinsky</h1></a>
    </div>
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
            <!--li><a href="/posts/">Posts</a></li-->
            <li><a href="/resume/">About</a></li>
            <li><a href="/projects/all/">Projects</a></li>
            <li><a href="/contact/">Contact</a></li>
        </ul>
    </div>
</nav>
{% endblock navbar %}

<div class="container torso">

    <div class="row">
        <div class="col col-lg-2 col-lg-offset-1 col-md-2 col-sm-2">
            <ul class="nav nav-pills nav-stacked sidebar hidden-xs">
                <!--li><a href="/posts/">Posts</a></li-->
                <li><a href="/resume/">About</a></li>
                <li><a href="/projects/all/">Projects</a></li>
                <li><a href="/contact/">Contact</a></li>
            </ul>
        </div>
    {% block container %}{% endblock container %}
    </div>
 </div>

<footer class="container">
<small>Copyright 2014 <a href="http://slipperyslo.pe">Philip Kalinsky</a>. <a href="/colophon/">Colophon</a>.</small>
</footer>
<!-- Le javascript
================================================== -->
{% block le_javascript %}{% endblock %}
</body>
</html>

mycv/apps/core/templates/resume.html
{% extends "base.html" %}
{% load staticfiles thumbnail %}

{% block container %}
<div class="col col-sm-10 col-md-8 col-lg-6 content">
    <article class="resume">

    <section id="resume">
    <div class="page-header no-top-margin"><h2>Resume</h2></div>
        <div class="row">
            <div class="col col-md-8 col-sm-12">
                        Skilled internet and client/server technologist
                    with over ten years of experience in the area of
                    software systems architecture  and development,
                    configuration management,
                    diagnostics and general IT expertise.
                    Proficient in web-based application development using Python and Ruby programming languages
                    with expert knowledge of numerous frameworks.
                    Possesses a strong understanding of core principles for advanced software
                    design and high quality code creation. Creativity, ability to achieve goals,
                    exceptional communication and interpersonal skills is an inherent asset.

                {% comment %} show email or address ?
                <div id="contact"><strong>Contact:</strong></div>
                <address>
                    4545 Center Blvd, Apt 406<br>
                    Long Island City, NY 11109<br>
                </address>
                <a href="mailto:{{ applicant.email }}">{{ applicant.email }}</a>
                {% endcomment %}

                {% if applicant.github_username %}
                <a style="padding-left:10px;" target="_blank" href="http://github.com/{{ applicant.github_username }}">
                    <img src="{% static 'img/GitHub-Mark-32px.png' %}">
                </a>
                {% endif %}
            </div>

            <div class="col-md-4 hidden-sm">
                {% comment %}
                <img src="{% static 'img/pk-200x212.png' %}" width="200" height="212"
                     align="right" style="padding: 0 0 20px 20px;" alt=""/>
                {% endcomment %}

                {% if applicant.avatar %}
                {% thumbnail applicant.avatar "200" crop="center" as image %}
                <img class="avatar" src="{{ image.url }}"
                     width="{{ image.width }}" height="{{ image.height }}"
                     align="right" style="padding: 0 0 20px 20px;">
                {% endthumbnail %}
                {% endif %}
            </div>
        </div>
    </section>

    <section id="experience"> </section>

    <section id="core">
        <ul id="tabs" class="nav nav-tabs">
            <li class="active">
                <a href="#tab0" data-toggle="tab"><h5>Professional Experience</h5></a>
            </li>
            <li class="">
                <a href="#tab1" data-toggle="tab"><h5>Core Skills</h5></a>
            </li>
            <li class="">
                <a href="#tab2" data-toggle="tab"><h5>Languages/Software</h5></a>
            </li>
            <!--li class="">
                <a href="#tab3" data-toggle="tab">Areas of interest</a>
            </li>
            <li class="">
                <a href="#tab4" data-toggle="tab">Software/Web Frameworks</a>
            </li-->
        </ul>
        <!--div class="page-header"><h2>Core Skills</h2></div-->


        <div class="module tab-content">
            <div class="tab-pane well active" id="tab0">
                {% include "_experience.html"%}
            </div>
            <div class="tab-pane well" id="tab1">
                {% include "_skills.html"%}
            </div>
            <div class="tab-pane well" id="tab2">
                <div class="cloud">
                    <p>Operating Systems/Hosting Platforms</p>
                    <span class="label label-inverse">Unix (Ubuntu, Debian Linux)</span>
                    <span class="label label-default">Amazon Web Services</span>
                    <span class="label label-default">Raskpace Cloud</span>
                    <span class="label label-default">Heroku</span>
                </div>
                <div class="cloud">
                    <p>Programming Languages</p>
                    <span class="label label-inverse">Python</span>
                    <span class="label label-default">Ruby</span>
                    <span class="label label-default">Java</span>
                    <span class="label label-default">Unix shell scripting</span>
                    <span class="label label-default">JavaScript</span>
                </div>

                <div class="cloud">
                    <p>Web Frameworks</p>
                    <span class="label label-inverse">Django</span>
                    <span class="label label-inverse">Flask</span>
                    <span class="label label-default">Zope/Plone</span>
                    <span class="label label-default">Ruby On Rails</span>

                    <div class="cloud">
                        <p>Libraries</p>
                        <span class="label label-default">Scrapy</span>
                        <span class="label label-default">Pinax</span>
                        <span class="label label-default">Funkload</span>
                        <span class="label label-default">Biopython</span>
                        <span class="label label-default">Elasticsearch</span>
                        <span class="label label-default">ZeroMQ</span>
                    </div>

                    <!--div class="cloud">
                        <p>Metrics</p>
                        <span class="label label-default">Graphite</span>
                    </div-->
                </div>
            </div>
            <!--div class="tab-pane well" id="tab3">
                <div class="cloud">
                    <ul>
                        <li>Web Frameworks</li>
                        <li>Devops</li>
                        <li>Messaging</li>
                        <li>Natural Language Processing</li>
                        <li>Machine Learning</li>
                    </ul>
                </div>
            </div-->
        </div><!-- /.tab-content -->
    </section>
    </article>
</div>
{% endblock %}